### ISSUE TITLE
demo error!!!

### ISSUE THREAD

**Issue by zx98cv12** [elye/loaderviewlibrary#5]
09-06 10:13:35.894 28244-28244/com.elyeproj.sampleloaderview E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.elyeproj.sampleloaderview, PID: 28244
                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.elyeproj.sampleloaderview/com.elyeproj.sampleloaderview.MainActivity}: android.view.InflateException: Binary XML file line #39: Error inflating class <unknown>
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2187)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:138)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5034)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
                                                                                   at com.android.internal.os.ZygoteInit.aurora_org_main(ZygoteInit.java:607)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
                                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                                Caused by: android.view.InflateException: Binary XML file line #39: Error inflating class <unknown>
                                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                   at com.elyeproj.sampleloaderview.MainActivity.onCreate(MainActivity.java:16)
                                                                                   at android.app.Activity.performCreate(Activity.java:5247)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                                   at com.lbe.security.service.core.client.b.v.callActivityOnCreate(Unknown Source)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2151)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:138) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5034) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791) 
                                                                                   at com.android.internal.os.ZygoteInit.aurora_org_main(ZygoteInit.java:607) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565) 
                                                                                   at dalvik.system.NativeStart.main(Native Method) 
                                                                                Caused by: java.lang.reflect.InvocationTargetException
                                                                                   at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                   at com.elyeproj.sampleloaderview.MainActivity.onCreate(MainActivity.java:16) 
                                                                                   at android.app.Activity.performCreate(Activity.java:5247) 
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                                   at com.lbe.security.service.core.client.b.v.callActivityOnCreate(Unknown Source) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2151) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:138) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5034) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791) 
                                                                                   at com.android.internal.os.ZygoteInit.aurora_org_main(ZygoteInit.java:607) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565) 
                                                                                   at dalvik.system.NativeStart.main(Native Method) 
                                                                                Caused by: java.lang.NullPointerException
                                                                                   at com.elyeproj.loaderviewlibrary.LoaderTextView.setRectColor(LoaderTextView.java:86)
                                                                                   at com.elyeproj.loaderviewlibrary.LoaderController.init(LoaderController.java:48)
                                                                                   at com.elyeproj.loaderviewlibrary.LoaderController.<init>(LoaderController.java:43)
                                                                                   at com.elyeproj.loaderviewlibrary.LoaderTextView.init(LoaderTextView.java:56)
                                                                                   at com.elyeproj.loaderviewlibrary.LoaderTextView.<init>(LoaderTextView.java:41)
                                                                                   at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                   at com.elyeproj.sampleloaderview.MainActivity.onCreate(MainActivity.java:16) 
                                                                                   at android.app.Activity.performCreate(Activity.java:5247) 
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                                   at com.lbe.security.service.core.client.b.v.callActivityOnCreate(Unknown Source) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2151) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:138) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5034) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791) 
                                                                                   at com.android.internal.os.ZygoteInit.aurora_org_main(ZygoteInit.java:607) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565) 
                                                                                   at dalvik.system.NativeStart.main(Native Method)

**Comment by LittleRobotRoad** [comment]
other loadertextview without android:textStyle="bold"，

solve  @Override
    public void setRectColor(Paint rectPaint) {
        final Typeface typeface = getTypeface();
        if (typeface != null && typeface.getStyle() == Typeface.BOLD) {
            rectPaint.setColor(LoaderConstant.COLOR_DARKER_GREY);
        } else {
            rectPaint.setColor(LoaderConstant.COLOR_DEFAULT_GREY);
        }
    }

**Comment by zx98cv12** [comment]
thank you !!!

**Comment by elye** [comment]
Thanks for reporting this issue. It has been fixed in version 1.1.1 and published.
